gits = [
("git@github.com:dormon/SDL2CPP.git"          ,""             ,[]),
("git@github.com:dormon/imguiDormon.git"      ,""             ,[]),
("git@github.com:dormon/imguiOpenGLDormon.git",""             ,[]),
("git@github.com:dormon/imguiSDL2Dormon.git"  ,""             ,[]),
("git@github.com:dormon/imguiSDL2OpenGL.git"  ,""             ,[]),
("git@github.com:dormon/geGL.git"             ,""             ,[]),
("git@github.com:dormon/BasicCamera.git"      ,""             ,[]),
("git@github.com:dormon/MealyMachine.git"     ,""             ,[]),
("git@github.com:dormon/TxtUtils.git"         ,""             ,[]),
("git@github.com:dormon/ArgumentViewer.git"   ,""             ,[]),
("git@github.com:dormon/Vars.git"             ,""             ,[]),
("git@github.com:dormon/checkRepos.git"       ,""             ,[]),
("git@github.com:dormon/prj.git"              ,""             ,[]),
("git@github.com:dormon/MemoryBandwidth.git"  ,""             ,[]),
("git@github.com:dormon/Shadows.git"            ,""             ,[]),
        ]
